version: '3.7'
services:
  catgpt:
    container_name: catgpt
    image: "cr.yandex/${registry_id}/myapp:v1"
    restart: always
    network_mode: "host"
 unifiedagent:
    container_name: unifiedagent
    image: "cr.yandex/yc/unified-agent"
    environment:
      FOLDER_ID: "${folder_id}"
    restart: allways
    network_mode: "host"
    volumes: 
      - /ua: /etc/yandex/unified-agent/conf.d